### ISSUE TITLE
Doesn't seem to be working with vhosts

### ISSUE THREAD

**Issue by RobertAudi** [desandro/windex#1]
I use windex loacally with MAMP Pro. I created a new vhost (http://php.sandbox:8888/) and the icons don't seem to get loaded. Everything else seems to work though. I also tried to add a .htaccess to the folder where the vhost is point to but that didn't fix things.

If I point the browser directly to the folder (http://localhost:8888/sandbox/php/) it works perfecty.

**Comment by desandro** [comment]
Closing this ancient issue. Please open a new issue if you run into this same problem.
